import { getEmailTemplates, getAgentEmailTemplates } from "@/lib/actions/email-templates";
import { TemplatesList } from "@/components/dashboard/leads/emails/templates-list";
import { GenerateOutreachSheet } from "@/components/dashboard/leads/emails/generate-outreach-sheet";
import { prisma } from "@/lib/prisma";
import Link from "next/link";
import { Bot, Mail, Plus } from "lucide-react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Email Templates | Dashboard",
};

export default async function EmailTemplatesPage() {
  const [templates, agentTemplates, latestBrief] = await Promise.all([
    getEmailTemplates(),
    getAgentEmailTemplates(),
    prisma.agentActionLog.findFirst({
      where: { agentId: "social-listening", status: "completed" },
      orderBy: { createdAt: "desc" },
    }),
  ]);

  const briefPayload = latestBrief?.payload as {
    stories?: { title: string; why: string }[];
    dataPoint?: string;
  } | null;

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-xl font-semibold">Email Templates</h1>
          <p className="text-sm text-muted-foreground mt-1">
            Create and manage reusable email templates for your leads.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <GenerateOutreachSheet />
          <Link
            href="/dashboard/leads/emails/new"
            className="inline-flex items-center gap-1.5 text-sm font-medium bg-foreground text-background px-3 py-1.5 rounded-lg hover:bg-foreground/90 transition-colors"
          >
            <Plus className="h-3.5 w-3.5" />
            New Template
          </Link>
        </div>
      </div>

      {/* Agent-generated templates section */}
      <div className="mb-8">
        <div className="flex items-center gap-2 mb-3">
          <span className="inline-flex items-center gap-1.5 bg-amber-100 text-amber-800 text-[11px] font-bold px-2.5 py-1 rounded-full tracking-wide">
            <Bot className="h-3 w-3" />
            AGENT TEMPLATES
          </span>
          <p className="text-xs text-muted-foreground">
            Auto-generated by the Social Listening Agent — content is AI-produced at runtime.
          </p>
        </div>

        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          {/* Morning Brief static card */}
          <div className="rounded-lg border border-amber-200 bg-amber-50/40 p-4 flex flex-col gap-3">
            <div className="flex items-start justify-between gap-2">
              <div className="min-w-0">
                <div className="flex items-center gap-1.5 mb-1">
                  <span className="inline-flex items-center gap-1 bg-amber-100 text-amber-800 text-[10px] font-bold px-1.5 py-0.5 rounded">
                    [AGENT: SOCIAL BRIEF]
                  </span>
                </div>
                <p className="font-medium text-sm truncate">Morning Brief (Agent)</p>
                <p className="text-xs text-muted-foreground truncate mt-0.5">
                  Afrova Morning Brief —{" "}
                  {latestBrief
                    ? new Date(latestBrief.createdAt).toLocaleDateString("en-GB", {
                        weekday: "long",
                        day: "numeric",
                        month: "long",
                      })
                    : "Not yet sent"}
                </p>
              </div>
              <Mail className="h-4 w-4 text-amber-600 shrink-0 mt-0.5" />
            </div>

            {briefPayload?.stories?.length ? (
              <p className="text-xs text-muted-foreground line-clamp-3 leading-relaxed">
                {briefPayload.stories[0].title}
                {briefPayload.stories.length > 1 && ` · ${briefPayload.stories[1].title}`}
              </p>
            ) : (
              <p className="text-xs text-muted-foreground italic">
                Runs automatically every day at 07:00 WAT via Trigger.dev.
              </p>
            )}

            <div className="flex items-center justify-between gap-2 pt-1 border-t border-amber-200/60 mt-auto">
              <p className="text-[11px] text-muted-foreground">
                {latestBrief
                  ? `Last sent ${new Date(latestBrief.createdAt).toLocaleDateString()}`
                  : "Awaiting first run"}
              </p>
              <p className="text-[11px] text-amber-700 font-medium">Daily · Automated</p>
            </div>
          </div>

          {/* Agent-generated email templates from content angles */}
          {agentTemplates.map((t) => (
            <div
              key={t.id}
              className="rounded-lg border border-amber-200 bg-amber-50/40 p-4 flex flex-col gap-3"
            >
              <div className="flex items-start justify-between gap-2">
                <div className="min-w-0">
                  <div className="flex items-center gap-1.5 mb-1">
                    <span className="inline-flex items-center gap-1 bg-amber-100 text-amber-800 text-[10px] font-bold px-1.5 py-0.5 rounded">
                      [AGENT: CONTENT ANGLE]
                    </span>
                  </div>
                  <p className="font-medium text-sm truncate">{t.name}</p>
                  <p className="text-xs text-muted-foreground truncate mt-0.5">{t.subject}</p>
                </div>
                <Mail className="h-4 w-4 text-amber-600 shrink-0 mt-0.5" />
              </div>

              <p className="text-xs text-muted-foreground line-clamp-3 leading-relaxed">
                {t.body.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim().slice(0, 120)}
                {t.body.length > 120 ? "…" : ""}
              </p>

              <div className="flex items-center justify-between gap-2 pt-1 border-t border-amber-200/60 mt-auto">
                <p className="text-[11px] text-muted-foreground">
                  Generated {new Date(t.createdAt).toLocaleDateString()}
                </p>
                <p className="text-[11px] text-amber-700 font-medium">AI-authored</p>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Manual templates */}
      <div>
        <p className="text-xs font-medium text-muted-foreground mb-3 uppercase tracking-wide">
          Manual Templates
        </p>
        <TemplatesList templates={templates} />
      </div>
    </div>
  );
}
